---
plugins:
    - 'prettier-plugin-tailwindcss'

tailwindConfig: 'tailwind.config.cjs'

overrides:
    - files: '*.astro'
      options:
          parser: 'astro'
          plugins:
              - 'prettier-plugin-astro'
