---
name: check-web

on:
  pull_request:
    paths:
      - "apps/web/**"
  merge_group: ~

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Check code
        run: bun --cwd apps/web lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build
        run: bun run --cwd apps/web build
