---
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "apps/web/**"
  pull_request:
    paths:
      - "apps/web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Resolve Dependencies
        run: bun install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Check code
        run: bun lint --cwd apps/web
      - name: Build
        run: bun build --cwd apps/web
